# single-node local proof config
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://localhost:8080
catalog.management=${ENV:CATALOG_MANAGEMENT}
query.max-memory=192MB
query.max-memory-per-node=128MB
query.max-total-memory=256MB
memory.heap-headroom-per-node=96MB
